name: CI for Java Invoice

on: [push]

jobs:

test:

name: Unit tests and Checkstyle

runs-on: ubuntu-latest

steps:

- uses: actions/checkout@v2

- name: Set up JDK

uses: actions/setup-java@v2

with:

java-version: '17'

distribution: 'adopt'

- name: Run tests and Checkstyle

run: mvn verify